### ISSUE TITLE
Project creation, app scheme and icon ready.

### ISSUE THREAD

**Issue by Bo0tStr4p** [PumpkinSoftware/TravelMate#16]
Time Spent: 
Andrea Asta: 4 hours

**Comment by Andreaasta** [comment]
Although the issue is closed, after the first feedback, we have arranged the graphics, a custom toolbar has been added for each page, the options page has been improved, the logo and font changed.

**Comment by Andreaasta** [comment]
Traslate app from english to italian
Time spent: 1h
