### ISSUE TITLE
Review System 

### ISSUE THREAD

**Issue by Andreaasta** [PumpkinSoftware/TravelMate#17]
- Feature name: How can you know people before you travel with them?
- Description: Providing users a review system(we thought about a system that uses stars such as rating in the online store) to know the other user behavior; we chose to make this feature because feedback advised us to take a profiling of people for increased security.
- Requires: adding logic to server, client side support.
- Due: Milestone 2
- Status: UI almost ready, other parts are missing.
- Time Estimation: 7 days.
Ivan: 1h
Andrea: 6h

**Comment by 666TheNumberOfTheBeast** [comment]
Add logic, interaction & layout

**Comment by Andreaasta** [comment]
Preparation of layouts and activities, the json post is missing
Time spent: 4h

**Comment by Andreaasta** [comment]
it works
Time spent: 2h
