### ISSUE TITLE
User page

### ISSUE THREAD

**Issue by 666TheNumberOfTheBeast** [PumpkinSoftware/TravelMate#19]
- Feature name: User profile
- Description: providing a classic user view with picture, username, bio, age, ...
- Requires: user interface, server (with database)
- Due: Milestone 2
- Status: user interface is ready, client-server interaction done.
- Time Estimation: 48 hours.

Ivan Fardin: 6 hours.
Andrea Asta : 2 hour.

**Comment by 666TheNumberOfTheBeast** [comment]
Add client-server interaction

**Comment by Andreaasta** [comment]
General restyling... all values are displayed correctly.
Time spent: 1h

**Comment by 666TheNumberOfTheBeast** [comment]
Fix loading bug

**Comment by 666TheNumberOfTheBeast** [comment]
Add edit profile button
