### ISSUE TITLE
Search page 

### ISSUE THREAD

**Issue by Andreaasta** [PumpkinSoftware/TravelMate#24]
- Feature name: How can you search trips?
- Description: providing a search view, user can select several filters and get trips
- Requires: user interface and server
- Due: Milestone 2
- Status: user interface and server are ready, interaction too
- Time Estimation: 48 hours.
Ivan Fardin: 16 hours.
Andrea Asta: 18 hours

**Comment by Andreaasta** [comment]
@666TheNumberOfTheBeast prepared a beautiful form

**Comment by Andreaasta** [comment]
I add toolbar and a page where you can see the seach results
Time : 2h

**Comment by Andreaasta** [comment]
connection with server worked, need to repair little bug
time : 5h

**Comment by Andreaasta** [comment]
Add value vehicle and tag events but a fix is required
Time spent: 4h

**Comment by 666TheNumberOfTheBeast** [comment]
Fix bug of click on search and client-server interaction, add possibility to uncheck radio buttons,
