### ISSUE TITLE
Login/Registration page 

### ISSUE THREAD

**Issue by Andreaasta** [PumpkinSoftware/TravelMate#3]
- Feature name: How can you access the app?
- Description: providing a classic login screen, login with social networks, google, outlook,...
- Requires: user interface, server(with database(?))  and then Google API, Oauth, Firebase(for statistics).
- Due: Milestone 2 (graphics for Milestone 1)
- Status: user interface is almost ready, other parts is missing.
- Time Estimation: 48 hours.
   Andrea Asta: 13 hours.
   Ivan Fardin: 14.5 hours.
   Romeo : 1.5 hours.

**Comment by Andreaasta** [comment]
la grafica è pronta al 90% manca il bottone social

**Comment by Andreaasta** [comment]
@666TheNumberOfTheBeast added video in background, fix bug of keyboard and prepared the space to insert social button login

**Comment by Andreaasta** [comment]
Added logout button in settings page

**Comment by Andreaasta** [comment]
@Bo0tStr4p has prepared the login with firebase and it works. The login is complete with email, autologin and logout button
Time spent: 1.5h

**Comment by 666TheNumberOfTheBeast** [comment]
Add different activities with transictions for ops. UI to be completed

**Comment by 666TheNumberOfTheBeast** [comment]
Add logic with Firebase

**Comment by 666TheNumberOfTheBeast** [comment]
Fix transitions

**Comment by Andreaasta** [comment]
Preparation form 
Time spent: 3h

**Comment by Andreaasta** [comment]
Starting preparation json...
Time spent: 3h

**Comment by Andreaasta** [comment]
Add firebase for register and error management.
Time spent: 2h

**Comment by 666TheNumberOfTheBeast** [comment]
Fix date picker

**Comment by 666TheNumberOfTheBeast** [comment]
Fix login & registration with all handling errors about email & password

**Comment by 666TheNumberOfTheBeast** [comment]
Add terms & conditions message with links

**Comment by Andreaasta** [comment]
@Bo0tStr4p Add image firebase management

**Comment by 666TheNumberOfTheBeast** [comment]
Add change Password in Settings, time spent for that is in Settings issue

**Comment by 666TheNumberOfTheBeast** [comment]
Fix finishing properly all starts activities when a user perform a registration

**Comment by 666TheNumberOfTheBeast** [comment]
Fix 1st interaction with server

**Comment by 666TheNumberOfTheBeast** [comment]
Add smart login (auto-detect spaces at email's end) & Fix finishing properly login activity when a user perform a registration

**Comment by 666TheNumberOfTheBeast** [comment]
Add possibility to show password & change layout
