### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by Andreaasta** [PumpkinSoftware/TravelMate#35]
- Feature name: Settings
- Description: User can find useful functions about app
- Requires: Client 
- Estimation: 2 d
Ivan: 3.5 h
Andrea: ...h

settings page prepared, but it needs restyling and it's only graphics.
Logout button works.

**Comment by 666TheNumberOfTheBeast** [comment]
Restyling

**Comment by 666TheNumberOfTheBeast** [comment]
Add twitter feed, social buttons & terms & conditions links

**Comment by 666TheNumberOfTheBeast** [comment]
Fix email intent, now it's open to all email app & not only to gmail

**Comment by 666TheNumberOfTheBeast** [comment]
Prepared delete user account
