### ISSUE TITLE
Viewing details of a trip

### ISSUE THREAD

**Issue by 666TheNumberOfTheBeast** [PumpkinSoftware/TravelMate#39]
- Feature name: How can you view details of a trip?
- Description: Providing a scrolling page with all info about it, so you can decide to join or not the group.
- Requires: user interface and server.
- Due: Milestone 2.
- Status: user interface ready while server and interaction yes
- Time Estimated: 2 days.
Ivan: 14.5 h
Andrea: 3h

**Comment by 666TheNumberOfTheBeast** [comment]
All dynamic except users

**Comment by Andreaasta** [comment]
Little restyling of cards with all value.
Starting function to receive partecipants.
Time spent: 3h

**Comment by 666TheNumberOfTheBeast** [comment]
Add recycler view for partecipants & join button animations

**Comment by 666TheNumberOfTheBeast** [comment]
Add logic to join button, particular string for current user in partecipant & edit button for owner

**Comment by 666TheNumberOfTheBeast** [comment]
Finished all logic about join button & refresh works properly on action; now errors from server are handled

**Comment by 666TheNumberOfTheBeast** [comment]
Minor fixes & prepared code to share "really" travels amongs users

**Comment by 666TheNumberOfTheBeast** [comment]
Fix api interaction in travel details & delete trip

**Comment by 666TheNumberOfTheBeast** [comment]
Fix bug of opening and closing quickly to show this page. Add also progress bar and its logic
