### ISSUE TITLE
MyTravel page

### ISSUE THREAD

**Issue by Andreaasta** [PumpkinSoftware/TravelMate#45]
- Feature name: personal travel page
- Description: a page where you can see your travels (scheduled, favorites, finished)
- Requires: api is ready, missing client
- Due: Milestone 2
- Status: 70%
- Time Estimation: 1d
Ivan: 3.2h
Andrea: 2.5h

**Comment by Andreaasta** [comment]
Ready to receive information from server

**Comment by Andreaasta** [comment]
Remove favourite column

**Comment by 666TheNumberOfTheBeast** [comment]
Add progress bar & Fix bug

**Comment by 666TheNumberOfTheBeast** [comment]
Fix auto-update when user create/delete travels in My Travels & Add "no travel to show" when required
