### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by Andreaasta** [PumpkinSoftware/TravelMate#49]
- Feature name: Chat 
- Description: chat between participants
- Requires: client and server are almost ready
- Due: Milestone 3
- Status: 80%
- Time Estimation: 2d
Romeo : 10h
Andrea : 5h
Ivan: 1h

**Comment by Andreaasta** [comment]
add chat button

**Comment by Andreaasta** [comment]
Starting chat
Time spent: 3h

**Comment by 666TheNumberOfTheBeast** [comment]
Fix showing recycler view & add lines separator amongs travels

**Comment by Andreaasta** [comment]
Add full chat feature, works correctly with text and images
Time spent:
Me : 2h
Romeo: 10h

**Comment by 666TheNumberOfTheBeast** [comment]
Restyling chat layout
