### ISSUE TITLE
Edit travel

### ISSUE THREAD

**Issue by 666TheNumberOfTheBeast** [PumpkinSoftware/TravelMate#55]
- Feature name: How can I edit a travel page if I am an organizer?
- Description: Clicking on the edit icon, a page like creation is opened
- Requires: Client & Server
- Due: Milestone 3
- Status: 100%
- Time Estimation: 3h
Ivan: 4.5h
Andrea: 1.5h

**Comment by 666TheNumberOfTheBeast** [comment]
Add all logic & layout, interaction must be fixed

**Comment by Andreaasta** [comment]
Add image firebase management (image)
Time spent: 1.5h

**Comment by 666TheNumberOfTheBeast** [comment]
Add all checks
