### ISSUE TITLE
Edit user profile

### ISSUE THREAD

**Issue by 666TheNumberOfTheBeast** [PumpkinSoftware/TravelMate#56]
- Feature name: How can I edit my profile?
- Description: Clicking on the edit icon, a page like registration is opened
- Requires: Client is almost ready, interaction with server completed
- Due: Milestone 3
- Status: 90%
- Time Estimation: 3h
Ivan: 5.5h
Andrea: 7h

**Comment by 666TheNumberOfTheBeast** [comment]
Add all logic & layout

**Comment by 666TheNumberOfTheBeast** [comment]
Improved icon color calculation in profile fragment

**Comment by Andreaasta** [comment]
Added firebase photo management
Time spent: 7h

**Comment by 666TheNumberOfTheBeast** [comment]
Add all checks

**Comment by 666TheNumberOfTheBeast** [comment]
Fix bug of empty bio
