### ISSUE TITLE
 Viewing trips (cards)

### ISSUE THREAD

**Issue by 666TheNumberOfTheBeast** [PumpkinSoftware/TravelMate#6]
- Feature name: How can you view trips?
- Description: providing a scrolling page to view trips.
- Requires: user interface and server.
- Due: Milestone 2 (graphics for Milestone 1).
- Status: user interface and server are ready, interaction too
- Time Estimated: 5 days.
   Ivan Fardin: 14 hours.
   Andrea Asta: 6.5 hours.

**Comment by Andreaasta** [comment]
@666TheNumberOfTheBeast Starting creation dynamic cards

**Comment by 666TheNumberOfTheBeast** [comment]
Add some logic to interact with dynamic cards

**Comment by 666TheNumberOfTheBeast** [comment]
Add transition to details activity

**Comment by Andreaasta** [comment]
trips are displayed correctly, the refresh is missing
Time spent: 1.5h

**Comment by 666TheNumberOfTheBeast** [comment]
Add progress bar

**Comment by Andreaasta** [comment]
Starting restyling cards 
Time spent; 2h
