### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by Andreaasta** [PumpkinSoftware/TravelMate#62]
- Feature name: Conversion token
- Description:  server communication conversion using tokens for greater security
- Requires: All
- Due: Milestone 3
- Status: 100%
- Time Estimation: 12h
Andrea: 3h
Romeo: 3h
Ivan: 3h

**Comment by Andreaasta** [comment]
@Bo0tStr4p he has prepared the server, now it is ready
Time spent: 3h

**Comment by Andreaasta** [comment]
App ready at 50%
Time spent: 3h

**Comment by 666TheNumberOfTheBeast** [comment]
Completed all remainings api's conversions
Time spent: 3 h
